### PR TITLE
Fixes #116

### LINKED ISSUE #116: Screen freezes temporarily when clicked on "Show all answers"
Not necessarily a show stopping issue but something that I found annoying. I'm guessing it's locking up the browser because of all the painting that's happening for answers.

### PR DESCRIPTION
**Pull request by shri3k**
- Screen no longer freezes for long period of time when clicked on "Show all answers"
- Tested only on Linux Chrome.

### CODE REVIEW

**Comment by morenoh149** [comment]
What is going on the `$().each()` and why does the `setTiimeout` fix the problem?
might be good to minimize the amount of code within the setTimeout.

**Comment by shri3k** [comment]
I would definitely would like to visit more on `each()` and what it's doing internally but thought it was a quick win(I know not a good practice :flushed: ) by just setting a timeout causing it to not block the rendering process.  
From a quick look at the devtools it showed me that it's taking some time for the render step to happen without `settimeout` (correct me if I'm wrong on this).  
The top one is the one with `setTimeout` and the bottom is the one without. 
learnrx_local1
learnrx_perf1
Notice that rendering is taking `~330ms` on the one without. I could be totally off here on reading the stats so if anyone has more knowledge on this can chime in.

**Comment by morenoh149** [comment]
I'll merge this in for now. May revisit in the future.

**Comment by shri3k** [comment]
Sounds good. I would like to dig deep into this in the future as well.

**Comment by morenoh149** [comment]
https://youtu.be/8aGhZQkoFbQ?t=14m59s call stack clearing issue?

**Comment by shri3k** [comment]
Yes, essentially the idea is to not clog the process into one long running stack but rather to clear the stack for user interaction and other processes.
I was actually looking for something close to `process.nextTick` but `setTimeout` is the closest that comes in browsers. And as you said, it's better to look more into the `each` than placing this workaround. I should have some time during this weekend. I'll try to figure out what's going on there.

**Pull request merged**
