### PR TITLE
#95: Check for valid JSON string before setting newState, #36: Implemented bootstrap modal with textarea

### PR DESCRIPTION
**Pull request by deepakshrma**

### CODE REVIEW

**Comment by morenoh149** [comment]
could you split these into two commits. And for UI changes please share a before and after screenshot.

**Comment by deepakshrma** [comment]
Done! Please check pull request  #97

**Comment by deepakshrma** [comment]
For second commit, I have added bootstrap to create modal pop up. Instead of window prompt. it will show bootstrap modal. Please refer to below given snapshots
```bash
#before:
```
screenshot from 2015-10-06 12 06 06

```bash
#after
```
desctop screenshot

**Comment by morenoh149** [comment]
Okay looks good since this project already has bootstrap as a dependency. Can you submit a seperate PR for the modal display.

**Comment by deepakshrma** [comment]
Done!! please check 
Pull request #98

**Pull request closed without merging**
